export const CONSTANTS = {
  ACCESS_TOKEN_KEY: "accessToken",
  REFRESH_TOKEN_KEY: "refreshToken",
  USER: "user",
};

export const ROUTES = {
  LOGIN_ROUTE: "/api/v1/auth/login",
  VERIFY_ME_ROUTE: "/api/v1/auth/me",
  REFRESH_TOKEN_ROUTE: "/api/v1/auth/refresh-token",
  GET_ALL_HOTELS_ROUTE: "/api/v1/hotels/",
  CREATE_HOTEL_ROUTE: "/api/v1/hotels/",
  GET_HOTEL_ROUTE: (hotelId: string) => `/api/v1/hotels/${hotelId}`,
  GET_CITIES_ROUTE: "/api/v1/cities/",
  GET_CITY_ROUTE: (cityId: string) => `/api/v1/cities/${cityId}`,
  CREATE_CITY_ROUTE: "/api/v1/cities/",
  UPDATED_CITY_ROUTE: (cityId: string) => `/api/v1/cities/${cityId}`,
  GET_ALL_USERS_ROUTE: (userType: string, page: number, limit: number) =>
    `/api/v1/auth/users?role=${userType}&page=${page}&limit=${limit}`,
  CREATE_HOTEL_ADMIN_ROUTE: "/api/v1/auth/addHotelAdmin",
  GET_HOTEL_ALLUSERS_ROUTE: "/api/v1/hotels/hotelUsers",
  GET_ALL_CITIES_ROUTE: "/api/v1/cities/",
  GET_HOTEL_ROOMS_ROUTE: (hotelId: string) => `/api/v1/hotels/${hotelId}/rooms`,
  CREATE_ROOM_ROUTE: (hotelId: string) => `/api/v1/hotels/${hotelId}/rooms`,
  UPDATE_ROOM_ROUTE: (hotelId: string, roomId: string) => `/api/v1/hotels/${hotelId}/rooms/${roomId}`,
  DELETE_ROOM_ROUTE: (hotelId: string, roomId: string) => `/api/v1/hotels/${hotelId}/rooms/${roomId}`,
  GET_ALL_ROOMS_ROUTE: "/api/v1/rooms/",
  GET_ROOMS_BY_HOTEL_ROUTE: "/api/v1/rooms/by-hotel",
  GET_ROOM_BY_ID_ROUTE: (roomId: string) => `/api/v1/rooms/${roomId}`,
  UPDATE_ROOM_BY_ID_ROUTE: (roomId: string) => `/api/v1/rooms/${roomId}`,
  DELETE_ROOM_BY_ID_ROUTE: (roomId: string) => `/api/v1/rooms/${roomId}`,
  CREATE_ROOM_DIRECT_ROUTE: "/api/v1/rooms/",
  GET_ROOM_TYPES_ROUTE: "/api/v1/room-types/",
  CREATE_ROOM_TYPE_ROUTE: "/api/v1/room-types/",
  GET_ROOM_TYPE_ROUTE: (roomTypeId: string) => `/api/v1/room-types/${roomTypeId}`,
  UPDATE_ROOM_TYPE_ROUTE: (roomTypeId: string) => `/api/v1/room-types/${roomTypeId}`,
  DELETE_ROOM_TYPE_ROUTE: (roomTypeId: string) => `/api/v1/room-types/${roomTypeId}`,
  GET_COUPONS_ROUTE: "/api/v1/coupons/",
  CREATE_COUPON_ROUTE: "/api/v1/coupons/",
  GET_COUPON_ROUTE: (couponId: string) => `/api/v1/coupons/${couponId}`,
  UPDATE_COUPON_ROUTE: (couponId: string) => `/api/v1/coupons/${couponId}`,
  DELETE_COUPON_ROUTE: (couponId: string) => `/api/v1/coupons/${couponId}`,
  GET_REVENUE_ROUTE: "/api/v1/revenue/",
  GET_REVENUE_RECORD_ROUTE: (recordId: string) => `/api/v1/revenue/${recordId}`,
  PAY_REVENUE_ROUTE: (recordId: string) => `/api/v1/revenue/${recordId}/pay`,
  UPDATE_REVENUE_STATUS_ROUTE: (recordId: string) => `/api/v1/revenue/${recordId}/status`,
  CREATE_PRICE_ADJUSTMENT_ROUTE: "/api/v1/pricing/adjust",
  GET_PRICE_ADJUSTMENTS_ROUTE: "/api/v1/pricing/history",
  GET_PRICE_ADJUSTMENT_ROUTE: (adjustmentId: string) => `/api/v1/pricing/${adjustmentId}`,
  UPDATE_PRICE_ADJUSTMENT_ROUTE: (adjustmentId: string) => `/api/v1/pricing/${adjustmentId}`,
  DELETE_PRICE_ADJUSTMENT_ROUTE: (adjustmentId: string) => `/api/v1/pricing/${adjustmentId}`,
  GET_INVOICES_ROUTE: "/api/v1/invoices/",
  CREATE_INVOICE_ROUTE: "/api/v1/invoices/",
  GET_INVOICE_ROUTE: (invoiceId: string) => `/api/v1/invoices/${invoiceId}`,
  UPDATE_INVOICE_STATUS_ROUTE: (invoiceId: string) => `/api/v1/invoices/${invoiceId}/status`,
  GENERATE_INVOICE_ROUTE: "/api/v1/invoices/generate",
  UPLOAD_IMAGES_BASE64_ROUTE: "/api/v1/upload/images/base64",
  DELETE_IMAGE_ROUTE: "/api/v1/upload/images",
  GET_DASHBOARD_ANALYTICS_ROUTE: (type: string, hotelId?: string) =>
    `/api/v1/analytics/dashboard?type=${type}${hotelId ? `&hotelId=${hotelId}` : ''}`,
  GET_CITY_ANALYTICS_ROUTE: (cityId: string) => `/api/v1/analytics/dashboard/cities/${cityId}`,
  GET_REVENUE_ANALYTICS_ROUTE: "/api/v1/analytics/revenue",
  GET_ALL_ROOM_TYPES: '/api/v1/room-types',
  // Addons routes
  GET_HOTEL_ADDONS_ROUTE: (hotelId: string, status: string = '') => `/api/v1/addons/hotels/${hotelId}/addons?status=${status}`,
  CREATE_HOTEL_ADDON_ROUTE: (hotelId: string) => `/api/v1/addons/hotels/${hotelId}/addons`,
  GET_ADDON_ROUTE: (hotelId: string, addonId: string) => `/api/v1/addons/hotels/${hotelId}/addons/${addonId}`,
  UPDATE_ADDON_ROUTE: (hotelId: string, addonId: string) => `/api/v1/addons/hotels/${hotelId}/addons/${addonId}`,
  DELETE_ADDON_ROUTE: (hotelId: string, addonId: string) => `/api/v1/addons/hotels/${hotelId}/addons/${addonId}`,
  GET_ROOM_ADDONS_ROUTE: (roomId: string) => `/api/v1/addons/rooms/${roomId}/addons`,
  UPDATE_ROOM_ADDONS_ROUTE: (hotelId: string, roomId: string) => `/api/v1/addons/hotels/${hotelId}/rooms/${roomId}/addons`,
  GET_AVAILABLE_ADDONS_ROUTE: (hotelId: string, roomId: string) => `/api/v1/addons/hotels/${hotelId}/rooms/${roomId}/available-addons`,
  // Hourly Stays Routes
  CREATE_HOURLY_STAY_ROUTE: "/api/v1/hourlyStays/hourly-stays",
  GET_HOURLY_STAYS_BY_ROOM_ROUTE: (roomId: string) => `/api/v1/hourlyStays/rooms/${roomId}/hourly-stays`,
  GET_HOURLY_STAYS_BY_HOTEL_ROUTE: (hotelId: string) => `/api/v1/hourlyStays/hotels/${hotelId}/hourly-stays`,
  UPDATE_HOURLY_STAY_ROUTE: (id: string) => `/api/v1/hourlyStays/hourly-stays/${id}`,
  DELETE_HOURLY_STAY_ROUTE: (id: string) => `/api/v1/hourlyStays/hourly-stays/${id}`,

  // Refund routes
  GET_REFUND_DETAILS_ROUTE: (refundId: string) => `/api/v1/details/refunds/${refundId}`,
  REFUNDS_LIST_ROUTE: "/api/v1/admin/refunds",

  // Wallet routes
  WALLET_USAGES_ROUTE: "/api/v1/details/walletusages",

  // Notification routes
  GET_NOTIFICATIONS_ROUTE: "/api/v1/notifications",
  MARK_NOTIFICATION_READ_ROUTE: (id: string) => `/api/v1/notifications/${id}/read`,
  MARK_ALL_NOTIFICATIONS_READ_ROUTE: "/api/v1/notifications/mark-all-read",
  DELETE_NOTIFICATION_ROUTE: (id: string) => `/api/v1/notifications/${id}`,
  BULK_DELETE_NOTIFICATIONS_ROUTE: "/api/v1/notifications/bulk-delete",
  WEB_PUSH_SUBSCRIBE_ROUTE: "/api/v1/web-push/subscribe",
  WEB_PUSH_UNSUBSCRIBE_ROUTE: "/api/v1/web-push/unsubscribe",
  WEB_PUSH_TEST_ROUTE: "/api/v1/web-push/test",
  WEB_PUSH_VAPID_KEY_ROUTE: "/api/v1/web-push/vapid-public-key",

  // Recent bookings route
  GET_RECENT_BOOKINGS_ROUTE: "/api/v1/bookings/recent",

  // Add other route constants as needed
} as const;

export const STATES_OPTIONS = [
  { label: "Andhra Pradesh", value: "AP" },
  { label: "Arunachal Pradesh", value: "AR" },
  { label: "Assam", value: "AS" },
  { label: "Bihar", value: "BR" },
  { label: "Chhattisgarh", value: "CG" },
  { label: "Goa", value: "GA" },
  { label: "Gujarat", value: "GJ" },
  { label: "Haryana", value: "HR" },
  { label: "Himachal Pradesh", value: "HP" },
  { label: "Jharkhand", value: "JH" },
  { label: "Karnataka", value: "KA" },
  { label: "Kerala", value: "KL" },
  { label: "Madhya Pradesh", value: "MP" },
  { label: "Maharashtra", value: "MH" },
  { label: "Manipur", value: "MN" },
  { label: "Meghalaya", value: "ML" },
  { label: "Mizoram", value: "MZ" },
  { label: "Nagaland", value: "NL" },
  { label: "Odisha", value: "OR" },
  { label: "Punjab", value: "PB" },
  { label: "Rajasthan", value: "RJ" },
  { label: "Sikkim", value: "SK" },
  { label: "Tamil Nadu", value: "TN" },
  { label: "Telangana", value: "TG" },
  { label: "Tripura", value: "TR" },
  { label: "Uttar Pradesh", value: "UP" },
  { label: "Uttarakhand", value: "UK" },
  { label: "West Bengal", value: "WB" },
];

export const AMENITIES_OPTIONS = [
  { label: "Free Wi-Fi", value: "free_wifi" },
  { label: "High-speed Internet", value: "high_speed_internet" },
  { label: "Air Conditioning", value: "air_conditioning" },
  { label: "Heating", value: "heating" },
  { label: "Climate Control", value: "climate_control" },
  { label: "Comfortable Bed & Pillows", value: "comfortable_bed_pillows" },
  { label: "Blackout Curtains", value: "blackout_curtains" },
  { label: "Desk & Chair", value: "desk_chair" },
  { label: "Wardrobe / Closet", value: "wardrobe_closet" },
  { label: "Luggage Rack", value: "luggage_rack" },
  { label: "In-room Safe", value: "in_room_safe" },
  { label: "Telephone", value: "telephone" },
  { label: "TV (Cable / Satellite / Streaming)", value: "tv_cable_satellite_streaming" },
  { label: "USB Charging Ports", value: "usb_charging_ports" },
  { label: "Electrical Outlets", value: "electrical_outlets" },
  { label: "Alarm Clock", value: "alarm_clock" },
  { label: "Wake-up Service", value: "wake_up_service" },
  { label: "Iron & Ironing Board", value: "iron_ironing_board" },
  { label: "Hair Dryer", value: "hair_dryer" },
  { label: "Bathrobes", value: "bathrobes" },
  { label: "Slippers", value: "slippers" },
  { label: "Towels", value: "towels" },
  { label: "Soap", value: "soap" },
  { label: "Shampoo", value: "shampoo" },
  { label: "Conditioner", value: "conditioner" },
  { label: "Lotion", value: "lotion" },
  { label: "Toothbrush", value: "toothbrush" },
  { label: "Toothpaste", value: "toothpaste" },
  { label: "Razor", value: "razor" },
  { label: "Shaving Kit", value: "shaving_kit" },
  { label: "Shower Cap", value: "shower_cap" },
  { label: "Vanity Kit", value: "vanity_kit" },
  { label: "Bathtub", value: "bathtub" },
  { label: "Shower", value: "shower" },
  { label: "Mini-fridge", value: "mini_fridge" },
  { label: "Minibar", value: "minibar" },
  { label: "Coffee Maker", value: "coffee_maker" },
  { label: "Tea Kettle", value: "tea_kettle" },
  { label: "Complimentary Bottled Water", value: "complimentary_bottled_water" },
  { label: "Kitchenette", value: "kitchenette" },
  { label: "Microwave", value: "microwave" },
  { label: "In-room Dining", value: "in_room_dining" },
  { label: "Hot & Cold Water", value: "hot_cold_water" },
  { label: "Rain Shower", value: "rain_shower" },
  { label: "Jacuzzi", value: "jacuzzi" },
  { label: "Whirlpool Tub", value: "whirlpool_tub" },
  { label: "Bidet", value: "bidet" },
  { label: "Magnifying Mirror", value: "magnifying_mirror" },
  { label: "Heated Towel Rack", value: "heated_towel_rack" },
  { label: "Complimentary Breakfast", value: "complimentary_breakfast" },
  { label: "Buffet Breakfast", value: "buffet_breakfast" },
  { label: "On-site Restaurant", value: "on_site_restaurant" },
  { label: "Bar", value: "bar" },
  { label: "Lounge", value: "lounge" },
  { label: "Café", value: "cafe" },
  { label: "Room Service", value: "room_service" },
  { label: "Mini Market", value: "mini_market" },
  { label: "Vending Machines", value: "vending_machines" },
  { label: "Swimming Pool", value: "swimming_pool" },
  { label: "Indoor Pool", value: "indoor_pool" },
  { label: "Outdoor Pool", value: "outdoor_pool" },
  { label: "Kids’ Pool", value: "kids_pool" },
  { label: "Fitness Center", value: "fitness_center" },
  { label: "Gym", value: "gym" },
  { label: "Spa", value: "spa" },
  { label: "Wellness Center", value: "wellness_center" },
  { label: "Sauna", value: "sauna" },
  { label: "Steam Room", value: "steam_room" },
  { label: "Hot Tub", value: "hot_tub" },
  { label: "Massage Services", value: "massage_services" },
  { label: "Yoga Classes", value: "yoga_classes" },
  { label: "Pilates Classes", value: "pilates_classes" },
  { label: "Beauty Salon", value: "beauty_salon" },
  { label: "Game Room", value: "game_room" },
  { label: "Library", value: "library" },
  { label: "Garden", value: "garden" },
  { label: "Terrace", value: "terrace" },
  { label: "Beach Access", value: "beach_access" },
  { label: "Sports Facilities", value: "sports_facilities" },
  { label: "Tennis Court", value: "tennis_court" },
  { label: "Golf Course", value: "golf_course" },
  { label: "Basketball Court", value: "basketball_court" },
  { label: "Bicycle Rentals", value: "bicycle_rentals" },
  { label: "Hiking Trails", value: "hiking_trails" },
  { label: "Water Sports Equipment", value: "water_sports_equipment" },
  { label: "Business Center", value: "business_center" },
  { label: "Meeting Rooms", value: "meeting_rooms" },
  { label: "Conference Facilities", value: "conference_facilities" },
  { label: "Printing Services", value: "printing_services" },
  { label: "Copying Services", value: "copying_services" },
  { label: "Audio-visual Equipment", value: "audio_visual_equipment" },
  { label: "24-hour Front Desk", value: "front_desk_24h" },
  { label: "Concierge Service", value: "concierge_service" },
  { label: "Bellhop", value: "bellhop" },
  { label: "Porter Service", value: "porter_service" },
  { label: "Express Check-in", value: "express_check_in" },
  { label: "Express Check-out", value: "express_check_out" },
  { label: "Mobile Check-in", value: "mobile_check_in" },
  { label: "Keyless Entry", value: "keyless_entry" },
  { label: "Currency Exchange", value: "currency_exchange" },
  { label: "Tour Desk", value: "tour_desk" },
  { label: "Ticket Assistance", value: "ticket_assistance" },
  { label: "Luggage Storage", value: "luggage_storage" },
  { label: "Safety Deposit Box", value: "safety_deposit_box" },
  { label: "Multilingual Staff", value: "multilingual_staff" },
  { label: "Cribs", value: "cribs" },
  { label: "Infant Beds", value: "infant_beds" },
  { label: "High Chairs", value: "high_chairs" },
  { label: "Kids’ Club", value: "kids_club" },
  { label: "Babysitting", value: "babysitting" },
  { label: "Childcare Services", value: "childcare_services" },
  { label: "Family Rooms", value: "family_rooms" },
  { label: "Play Area", value: "play_area" },
  { label: "Free Parking", value: "free_parking" },
  { label: "Valet Parking", value: "valet_parking" },
  { label: "Secure Parking", value: "secure_parking" },
  { label: "Airport Shuttle", value: "airport_shuttle" },
  { label: "Local Shuttle", value: "local_shuttle" },
  { label: "Car Rental Desk", value: "car_rental_desk" },
  { label: "Bicycle Parking", value: "bicycle_parking" },
  { label: "Wheelchair Accessible Rooms", value: "wheelchair_accessible_rooms" },
  { label: "Accessible Bathrooms", value: "accessible_bathrooms" },
  { label: "Elevator", value: "elevator" },
  { label: "Braille Signage", value: "braille_signage" },
  { label: "Assistive Listening Devices", value: "assistive_listening_devices" },
  { label: "Butler Service", value: "butler_service" },
  { label: "Welcome Drinks", value: "welcome_drinks" },
  { label: "Welcome Snacks", value: "welcome_snacks" },
  { label: "Turn-down Service", value: "turn_down_service" },
  { label: "Pillow Menu", value: "pillow_menu" },
  { label: "Personalized Gifts", value: "personalized_gifts" },
  { label: "In-room Aromatherapy", value: "in_room_aromatherapy" },
  { label: "Themed Rooms", value: "themed_rooms" },
  { label: "Private Pool", value: "private_pool" },
  { label: "Private Jacuzzi", value: "private_jacuzzi" },
  { label: "Rooftop Bar", value: "rooftop_bar" },
  { label: "Wine Cellar", value: "wine_cellar" },
  { label: "Wine Tasting Events", value: "wine_tasting_events" },
  { label: "Energy-saving Lighting", value: "energy_saving_lighting" },
  { label: "Water-saving Fixtures", value: "water_saving_fixtures" },
  { label: "Organic Toiletries", value: "organic_toiletries" },
  { label: "Recycling Bins", value: "recycling_bins" },
  { label: "Towel Reuse Program", value: "towel_reuse_program" },
  { label: "Linen Reuse Program", value: "linen_reuse_program" },
  { label: "Solar Power", value: "solar_power" },
  { label: "Renewable Energy", value: "renewable_energy" },
  { label: "Non-toxic Cleaning Products", value: "non_toxic_cleaning_products" }
];

export const ROOM_AMENITIES_OPTIONS = [
  { label: "Free Wi-Fi", value: "free_wifi" },
  { label: "Swimming Pool", value: "swimming_pool" },
  { label: "Fitness Center", value: "fitness_center" },
  { label: "Spa", value: "spa" },
  { label: "Room Service", value: "room_service" },
  { label: "AC / Heating", value: "ac_heating" },
  { label: "Parking", value: "parking" },
  { label: "TV", value: "tv" },
  { label: "Minibar", value: "minibar" },
  { label: "Balcony", value: "balcony" },
  { label: "Pet Friendly", value: "pet_friendly" },
  { label: "Safe", value: "safe" },
  { label: "Coffee Maker", value: "coffee_maker" },
  { label: "Hair Dryer", value: "hair_dryer" },
  { label: "Iron", value: "iron" },
  { label: "Bathrobe", value: "bathrobe" },
  { label: "Slippers", value: "slippers" },
];

export const ROOM_TYPES = [
  { label: "Standard Room", value: "standard" },
  { label: "Deluxe Room", value: "deluxe" },
  { label: "Suite", value: "suite" },
  { label: "Executive Room", value: "executive" },
  { label: "Presidential Suite", value: "presidential" },
  { label: "Family Room", value: "family" },
  { label: "Single Room", value: "single" },
  { label: "Double Room", value: "double" },
  { label: "Twin Room", value: "twin" },
];