export const CONSTANTS = {
  ACCESS_TOKEN_KEY: "accessToken",
  REFRESH_TOKEN_KEY: "refreshToken",
  USER: "user",
};

export const ROUTES = {
  LOGIN_ROUTE: "/api/v1/auth/login",
  VERIFY_ME_ROUTE: "/api/v1/auth/me",
  REFRESH_TOKEN_ROUTE: "/api/v1/auth/refresh-token",
  GET_ALL_HOTELS_ROUTE: "/api/v1/hotels/",
  CREATE_HOTEL_ROUTE: "/api/v1/hotels/",
  GET_HOTEL_ROUTE: (hotelId: string) => `/api/v1/hotels/${hotelId}`,
  GET_CITIES_ROUTE: "/api/v1/cities/",
  GET_CITY_ROUTE: (cityId: string) => `/api/v1/cities/${cityId}`,
  CREATE_CITY_ROUTE: "/api/v1/cities/",
  UPDATED_CITY_ROUTE: (cityId: string) => `/api/v1/cities/${cityId}`,
  GET_ALL_USERS_ROUTE: (userType: string, page: number, limit: number) =>
    `/api/v1/auth/users?role=${userType}&page=${page}&limit=${limit}`,
  CREATE_HOTEL_ADMIN_ROUTE: "/api/v1/auth/addHotelAdmin",
  GET_HOTEL_ALLUSERS_ROUTE: "/api/v1/hotels/hotelUsers",
  GET_ALL_CITIES_ROUTE: "/api/v1/cities/",
  GET_HOTEL_ROOMS_ROUTE: (hotelId: string) => `/api/v1/hotels/${hotelId}/rooms`,
  CREATE_ROOM_ROUTE: (hotelId: string) => `/api/v1/hotels/${hotelId}/rooms`,
  UPDATE_ROOM_ROUTE: (hotelId: string, roomId: string) => `/api/v1/hotels/${hotelId}/rooms/${roomId}`,
  DELETE_ROOM_ROUTE: (hotelId: string, roomId: string) => `/api/v1/hotels/${hotelId}/rooms/${roomId}`,
  GET_ROOM_TYPES_ROUTE: "/api/v1/room-types/",
  CREATE_ROOM_TYPE_ROUTE: "/api/v1/room-types/",
  GET_ROOM_TYPE_ROUTE: (roomTypeId: string) => `/api/v1/room-types/${roomTypeId}`,
  UPDATE_ROOM_TYPE_ROUTE: (roomTypeId: string) => `/api/v1/room-types/${roomTypeId}`,
  DELETE_ROOM_TYPE_ROUTE: (roomTypeId: string) => `/api/v1/room-types/${roomTypeId}`,
  GET_COUPONS_ROUTE: "/api/v1/coupons/",
  CREATE_COUPON_ROUTE: "/api/v1/coupons/",
  GET_COUPON_ROUTE: (couponId: string) => `/api/v1/coupons/${couponId}`,
  UPDATE_COUPON_ROUTE: (couponId: string) => `/api/v1/coupons/${couponId}`,
  DELETE_COUPON_ROUTE: (couponId: string) => `/api/v1/coupons/${couponId}`,
  GET_REVENUE_ROUTE: "/api/v1/revenue/",
  GET_REVENUE_RECORD_ROUTE: (recordId: string) => `/api/v1/revenue/${recordId}`,
  PAY_REVENUE_ROUTE: (recordId: string) => `/api/v1/revenue/${recordId}/pay`,
  UPDATE_REVENUE_STATUS_ROUTE: (recordId: string) => `/api/v1/revenue/${recordId}/status`,
  CREATE_PRICE_ADJUSTMENT_ROUTE: "/api/v1/pricing/adjust",
  GET_PRICE_ADJUSTMENTS_ROUTE: "/api/v1/pricing/history",
  GET_PRICE_ADJUSTMENT_ROUTE: (adjustmentId: string) => `/api/v1/pricing/${adjustmentId}`,
  UPDATE_PRICE_ADJUSTMENT_ROUTE: (adjustmentId: string) => `/api/v1/pricing/${adjustmentId}`,
  DELETE_PRICE_ADJUSTMENT_ROUTE: (adjustmentId: string) => `/api/v1/pricing/${adjustmentId}`,
  GET_INVOICES_ROUTE: "/api/v1/invoices/",
  CREATE_INVOICE_ROUTE: "/api/v1/invoices/",
  GET_INVOICE_ROUTE: (invoiceId: string) => `/api/v1/invoices/${invoiceId}`,
  UPDATE_INVOICE_STATUS_ROUTE: (invoiceId: string) => `/api/v1/invoices/${invoiceId}/status`,
  GENERATE_INVOICE_ROUTE: "/api/v1/invoices/generate",
  UPLOAD_IMAGES_BASE64_ROUTE: "/api/v1/upload/images/base64",
  DELETE_IMAGE_ROUTE: "/api/v1/upload/images",
  GET_DASHBOARD_ANALYTICS_ROUTE: (type: string, hotelId?: string) => 
    `/api/v1/analytics/dashboard?type=${type}${hotelId ? `&hotelId=${hotelId}` : ''}`,
  GET_CITY_ANALYTICS_ROUTE: (cityId: string) => `/api/v1/analytics/cities/${cityId}`,
  GET_REVENUE_ANALYTICS_ROUTE: "/api/v1/analytics/revenue",
};

export const STATES_OPTIONS = [
  { label: "Andhra Pradesh", value: "AP" },
  { label: "Arunachal Pradesh", value: "AR" },
  { label: "Assam", value: "AS" },
  { label: "Bihar", value: "BR" },
  { label: "Chhattisgarh", value: "CG" },
  { label: "Goa", value: "GA" },
  { label: "Gujarat", value: "GJ" },
  { label: "Haryana", value: "HR" },
  { label: "Himachal Pradesh", value: "HP" },
  { label: "Jharkhand", value: "JH" },
  { label: "Karnataka", value: "KA" },
  { label: "Kerala", value: "KL" },
  { label: "Madhya Pradesh", value: "MP" },
  { label: "Maharashtra", value: "MH" },
  { label: "Manipur", value: "MN" },
  { label: "Meghalaya", value: "ML" },
  { label: "Mizoram", value: "MZ" },
  { label: "Nagaland", value: "NL" },
  { label: "Odisha", value: "OR" },
  { label: "Punjab", value: "PB" },
  { label: "Rajasthan", value: "RJ" },
  { label: "Sikkim", value: "SK" },
  { label: "Tamil Nadu", value: "TN" },
  { label: "Telangana", value: "TG" },
  { label: "Tripura", value: "TR" },
  { label: "Uttar Pradesh", value: "UP" },
  { label: "Uttarakhand", value: "UK" },
  { label: "West Bengal", value: "WB" },
];

export const AMENITIES_OPTIONS = [
  { label: "WiFi", value: "wifi" },
  { label: "Pool", value: "pool" },
  { label: "Gym", value: "gym" },
  { label: "Restaurant", value: "restaurant" },
  { label: "Spa", value: "spa" },
  { label: "Parking", value: "parking" },
  { label: "Room Service", value: "room_service" },
  { label: "Business Center", value: "business_center" },
];

export const ROOM_AMENITIES_OPTIONS = [
  { label: "Free Wi-Fi", value: "free_wifi" },
  { label: "Swimming Pool", value: "swimming_pool" },
  { label: "Fitness Center", value: "fitness_center" },
  { label: "Spa", value: "spa" },
  { label: "Room Service", value: "room_service" },
  { label: "AC / Heating", value: "ac_heating" },
  { label: "Parking", value: "parking" },
  { label: "TV", value: "tv" },
  { label: "Minibar", value: "minibar" },
  { label: "Balcony", value: "balcony" },
  { label: "Pet Friendly", value: "pet_friendly" },
  { label: "Safe", value: "safe" },
  { label: "Coffee Maker", value: "coffee_maker" },
  { label: "Hair Dryer", value: "hair_dryer" },
  { label: "Iron", value: "iron" },
  { label: "Bathrobe", value: "bathrobe" },
  { label: "Slippers", value: "slippers" },
];

export const ROOM_TYPES = [
  { label: "Standard Room", value: "standard" },
  { label: "Deluxe Room", value: "deluxe" },
  { label: "Suite", value: "suite" },
  { label: "Executive Room", value: "executive" },
  { label: "Presidential Suite", value: "presidential" },
  { label: "Family Room", value: "family" },
  { label: "Single Room", value: "single" },
  { label: "Double Room", value: "double" },
  { label: "Twin Room", value: "twin" },
];
